Repository flyve-mdm/deeplink, pull requests merged in 2018-05, with the labels that each got.

#20 Bigger QR image
  index.html
  js/script.js
Labels: refactor

#23 Automatic deploy to gh-pages
  .circleci/config.yml
  ci/scripts/deploy.sh
  ci/scripts/git_config.sh
  package.json
  site/LICENSE
  site/README.md
  site/css/fonts/selawk.ttf
  site/css/normalize.css
  site/css/style.css
  site/img/forward.png
  site/img/logo.png
  site/img/logo2.png
  site/index.html
  site/js/bugsnag-3.min.js
  site/js/getData.js
  site/js/qrious.js
  site/js/script.js
  yarn.lock
Labels: build, ci

#25 CI/CD fails
  ci/scripts/deploy.sh
Labels: bug, ci

#27 Update 'node' on CircleCI
  .circleci/config.yml
Labels: ci
